### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by andrew--r** [HugoGiraudel/SJSJ#102]
Hi!

May I translate this repo into Russian?

**Comment by KittyGiraudel** [comment]
Hi.

On paper I’m all for. However it grows very fast and I’m afraid you’ll have a hard time keeping up with the translations. What do you think?

If you do, please fork it rather than creating a new repo from scratch. I’ll be sure to add a link to your translation in the README. :)

**Comment by andrew--r** [comment]
Thanks! I'll start translation soon. I will ask some russian developers to help me, so I hope it wouldn't take too much time.

**Comment by KittyGiraudel** [comment]
Please ping me on this issue when you feel like we can link to your translation on the main README. In the mean time, I’m closing. :)

**Comment by virtyaluk** [comment]
@HugoGiraudel 
@andrew--r 
I believe it would be nice to create GitHub organization (named SJSJ) and then host all the translations under that organization. So, it will be much easier to keep track of any changes\updates.I would love to make a contribution to english, russian, ukrainian and maybe polish forks.

**Comment by KittyGiraudel** [comment]
Hey. Let me think about this for a while, I’ll come back to you. :)

**Comment by KittyGiraudel** [comment]
Alright so I am coming back to this. I am divided I must say.

On one hand, I am glad that some people are willing to invest time and efforts into translations. I think it is great. This is thanks to those people that http://sass-guidelin.es currently exists in 12 languages.

On the other, I feel like this project actually should not really be translated. The whole point is to explain words, terms and expressions from the JavaScript ecosystem. These expression are in English because this is the way things are. Translating theme would defeat the initial purpose. Of course, we could still translate the explanations, but I feel like it is not entirely necessary. I might be wrong though.

On top of that, managing translations is one hell of a job. I spend several hours a week on Sass Guidelines trying to get contributors to update their translation because I care about having all the translations at the same level of content. At the same time, I cannot force them to do so because they are volunteer contributors, and I am super glad that they are willing to contribute. Finding the balance is very hard and I don’t feel like engaging myself into this again on a second project.

Now, if another contributor (or severals) are willing to translate and maintain up to date SJSJ into a 3rd language, I will reconsider my position. At this point, we will discuss moving this project to an organisation, and offering writing privileges to most active contributors for instance.

I hope I don’t appear as insensitive saying all this. I am of course open for discussion.

**Comment by virtyaluk** [comment]
Well said! I respect your point of view.

I was thinking about it lately and realized that yes, it could be hard to house all translations under the one organization, and much harder to keep all the translations in sync. For example, there's the fork with Russian translations and it's just a FORK. So to move it to the organization the author must create a separate repository containing all the files from the original fork. Doing so might frighten away some contributors.

Nevertheless, moving this repo to separate organization is the next step in the development of the project. I would say, now is the time to move from the status "personal project" to the status of "community project".

P.S. Having such an organization will allow to easily manage the other translations in the future.
